import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import dynamic from 'next/dynamic'

const DynamicEmailComponent = dynamic(() => import('../components/Email'))

export default function Home() {
  const [checked, setChecked] = useState(false)

  const handleChange = () => {
    console.log('checked: ', checked)
    console.log('Clicked!')
    setChecked(!checked)
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>Show email field? {JSON.stringify(checked)}</p>
        <label>
          <input type="checkbox" checked={checked} onChange={handleChange} />
          Click to show email field
        </label>
        <br />

        {checked && <DynamicEmailComponent />}
      </main>
    </div>
  )
}
